
/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/
USE [master]
GO

/****** Object:  Database [DMP_Wescola]    Script Date: 11/30/2017 5:47:33 PM ******/
CREATE DATABASE [DMP_Wescola]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DMP_Wescola', FILENAME = N'C:\Users\Jeferson\DMP_Wescola.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DMP_Wescola_log', FILENAME = N'C:\Users\Jeferson\DMP_Wescola_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DMP_Wescola] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DMP_Wescola].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DMP_Wescola] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [DMP_Wescola] SET ANSI_NULLS OFF
GO

ALTER DATABASE [DMP_Wescola] SET ANSI_PADDING OFF
GO

ALTER DATABASE [DMP_Wescola] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [DMP_Wescola] SET ARITHABORT OFF
GO

ALTER DATABASE [DMP_Wescola] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [DMP_Wescola] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [DMP_Wescola] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [DMP_Wescola] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [DMP_Wescola] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [DMP_Wescola] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [DMP_Wescola] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [DMP_Wescola] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [DMP_Wescola] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [DMP_Wescola] SET  ENABLE_BROKER
GO

ALTER DATABASE [DMP_Wescola] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [DMP_Wescola] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [DMP_Wescola] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [DMP_Wescola] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [DMP_Wescola] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [DMP_Wescola] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [DMP_Wescola] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [DMP_Wescola] SET RECOVERY SIMPLE
GO

ALTER DATABASE [DMP_Wescola] SET  MULTI_USER
GO

ALTER DATABASE [DMP_Wescola] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [DMP_Wescola] SET DB_CHAINING OFF
GO

ALTER DATABASE [DMP_Wescola] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [DMP_Wescola] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [DMP_Wescola] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [DMP_Wescola] SET QUERY_STORE = OFF
GO

USE [DMP_Wescola]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [DMP_Wescola]
GO

/****** Object:  Table [adm].[AD_MUNICIPIO]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [adm].[AD_ORGAOEMISSOR]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [adm].[AD_UF]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AD_ACOES]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AD_MENU]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AD_MODULOS]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AD_ORGAOS]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AD_REFRESHTOKEN]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AD_REFRESHTOKENHISTORY]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AspNetRoles]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AspNetUserClaims]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AspNetUserLogins]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AspNetUserRoles]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AspNetUsers]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_AVALIACAO]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_AVALIACAOOBSERVACAO]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_AVALIACAOPERGUNTA]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_CLIENTE]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_CONTROLENECESSIDADE]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_DIVULGACAO]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_DIVULGACAOENVIOS]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_ESCOLARIDADE]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_EVENTO]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_EVENTODATAS]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_EVENTOTURNOS]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_GRUPODEQUESTOES]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_INSCRICAO]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_LOCALEVENTO]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_LOCALPROVA]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_NECESSIDADE]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_PROVAQUESTOES]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_QUESTOESCORRECAO]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_RECURSOPROVA]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_SALALOCALPROVA]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_SITUACAOEVENTO]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_TEMA]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_TIPOEVENTO]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[EV_TPNECESSIDADE]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [escola].[ES_DEPENDENCIAADMINISTRATIVA]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [escola].[ES_INSTITUICOES]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [escola].[ES_LISTAATIVIDADES]    Script Date: 11/30/2017 5:47:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING ON
GO

USE [master]
GO

ALTER DATABASE [DMP_Wescola] SET  READ_WRITE
GO
