CREATE TABLE [dbo].[AD_ACOES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ACOES] [varchar](250) NOT NULL,
	[MODULOID] [int] NOT NULL,
	[LINK] [varchar](250) NULL,
	[ICONE] [varchar](50) NULL,
	[ORDEM] [int] NULL,
 CONSTRAINT [PK_ADMIN_ACOES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
ALTER TABLE [dbo].[AD_ACOES]  WITH CHECK ADD  CONSTRAINT [FK_AD_ACOES_AD_MODULOS] FOREIGN KEY([MODULOID])
REFERENCES [dbo].[AD_MODULOS] ([ID])
GO

ALTER TABLE [dbo].[AD_ACOES] CHECK CONSTRAINT [FK_AD_ACOES_AD_MODULOS]