CREATE TABLE [dbo].[AD_MENU](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MENU] [varchar](250) NOT NULL,
	[ACOESID] [int] NOT NULL,
	[LINK] [varchar](250) NULL,
	[ORDEM] [int] NULL,
	[ATIVO] [bit] NULL,
 CONSTRAINT [PK_AD_MENU] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
ALTER TABLE [dbo].[AD_MENU]  WITH CHECK ADD  CONSTRAINT [FK_AD_MENU_AD_ACOES] FOREIGN KEY([ACOESID])
REFERENCES [dbo].[AD_ACOES] ([ID])
GO

ALTER TABLE [dbo].[AD_MENU] CHECK CONSTRAINT [FK_AD_MENU_AD_ACOES]