CREATE TABLE [dbo].[AD_MODULOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MODULO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ADMIN_MODULOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

