CREATE TABLE [dbo].[AD_REFRESHTOKENHISTORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDREFRESHTOKEN] [int] NOT NULL,
	[USERID] [nvarchar](128) NOT NULL,
	[HASH] [varchar](50) NOT NULL,
	[PROTECTEDTICKET] [varchar](max) NOT NULL,
	[DTEMISSAO] [datetime] NOT NULL,
	[DTEMISSAOUTC] [datetime] NOT NULL,
	[DTEXPIRACAO] [datetime] NOT NULL,
	[DTEXPIRACAOUTC] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

