CREATE TABLE [dbo].[EV_CLIENTE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [nvarchar](128) NOT NULL,
	[NOME] [varchar](250) NULL,
	[EMAIL] [varchar](50) NULL,
	[RG] [varchar](50) NULL,
	[ORGAOEMISSOR] [varchar](50) NULL,
	[UFEMISSOR] [varchar](5) NULL,
	[DTEMISSAO] [datetime] NOT NULL,
	[CPF] [varchar](50) NULL,
	[NACIONALIDADE] [varchar](50) NULL,
	[NATURALIDADE] [varchar](50) NULL,
	[DTNASCIMENTO] [datetime] NULL,
	[SEXO] [varchar](50) NULL,
	[NOMEPAI] [varchar](250) NULL,
	[NOMEMAE] [varchar](250) NULL,
	[CEP] [varchar](50) NULL,
	[ENDERECO] [varchar](250) NULL,
	[BAIRRO] [varchar](250) NULL,
	[NUMERO] [int] NULL,
	[COMPLEMENTO] [varchar](250) NULL,
	[CIDADE] [varchar](250) NULL,
	[ESTADO] [varchar](5) NULL,
	[TEL_RESIDENCIAL] [varchar](50) NULL,
	[TEL_COMERCIAL] [varchar](50) NULL,
	[TEL_CELULAR] [varchar](50) NULL,
	[SENHA] [varchar](250) NULL,
	[CAD_ADMINISTRACAO] [varchar](10) NULL,
	[ENVIO_SENHA] [varchar](5) NULL,
	[ORGAOTRABALHOID] [int] NULL,
	[ESCOLARIDADEID] [int] NULL,
	[INSTITUICAO] [varchar](250) NULL,
	[DTCONCLUSAO] [datetime] NULL,
	[DTCADASTRO] [datetime] NULL,
	[DTALTERACAO] [datetime] NULL,
	[DTULTIMOACESSO] [datetime] NULL,
	[IDANTIGO] [bigint] NULL,
	[IDORGAOANTIGO] [int] NULL,
	[IDESCOLARIDADEANTIGO] [int] NULL,
	[QTDACESSO] [int] NULL,
	[RECEBERFEEDS] [int] NULL,
	[DTEXCLUSAO] [datetime] NULL,
 CONSTRAINT [PK_EV_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
/****** Object:  Index [NonClusteredIndex-20171012-191301]    Script Date: 11/30/2017 5:47:33 PM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20171012-191301] ON [dbo].[EV_CLIENTE]
(
	[IDANTIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


GO
/****** Object:  Index [NonClusteredIndex-20171019-223308]    Script Date: 11/30/2017 5:47:33 PM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20171019-223308] ON [dbo].[EV_CLIENTE]
(
	[NOME] ASC,
	[EMAIL] ASC,
	[RG] ASC,
	[CPF] ASC,
	[SEXO] ASC,
	[CIDADE] ASC,
	[ESTADO] ASC,
	[TEL_CELULAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


GO
ALTER TABLE [dbo].[EV_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_EV_CLIENTE_EV_ESCOLARIDADE] FOREIGN KEY([ESCOLARIDADEID])
REFERENCES [dbo].[EV_ESCOLARIDADE] ([ID])
GO

ALTER TABLE [dbo].[EV_CLIENTE] CHECK CONSTRAINT [FK_EV_CLIENTE_EV_ESCOLARIDADE]
GO
ALTER TABLE [dbo].[EV_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_EV_CLIENTE_AspNetUsers] FOREIGN KEY([USERID])
REFERENCES [dbo].[AspNetUsers] ([Id])
GO

ALTER TABLE [dbo].[EV_CLIENTE] CHECK CONSTRAINT [FK_EV_CLIENTE_AspNetUsers]
GO
ALTER TABLE [dbo].[EV_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_EV_CLIENTE_AD_ORGAOS] FOREIGN KEY([ORGAOTRABALHOID])
REFERENCES [dbo].[AD_ORGAOS] ([ID])
GO

ALTER TABLE [dbo].[EV_CLIENTE] CHECK CONSTRAINT [FK_EV_CLIENTE_AD_ORGAOS]