CREATE TABLE [dbo].[EV_DIVULGACAO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITULO] [varchar](250) NOT NULL,
	[MENSAGEM] [varchar](max) NOT NULL,
	[DTCRIACAO] [datetime] NOT NULL,
	[DTALTERACAO] [datetime] NOT NULL,
 CONSTRAINT [PK_EV_DIVULGACAO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

