CREATE TABLE [dbo].[EV_DIVULGACAOENVIOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDDIVULGACAO] [int] NOT NULL,
	[IDEVENTO] [int] NULL,
	[IDORGAOTRABALHO] [int] NULL,
	[DSLETRAALFABETO] [varchar](1) NULL,
	[EMAILTESTE] [varchar](50) NULL,
	[EMAILREMETENTE] [varchar](50) NOT NULL,
	[ASSUNTO] [varchar](50) NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[DTALTERACAO] [datetime] NOT NULL,
	[DTEXCLUSAO] [datetime] NULL,
 CONSTRAINT [PK_EV_DIVULGACAOENVIOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
ALTER TABLE [dbo].[EV_DIVULGACAOENVIOS]  WITH CHECK ADD  CONSTRAINT [FK_EV_DIVULGACAOENVIOS_EV_EVENTO] FOREIGN KEY([IDEVENTO])
REFERENCES [dbo].[EV_EVENTO] ([ID])
GO

ALTER TABLE [dbo].[EV_DIVULGACAOENVIOS] CHECK CONSTRAINT [FK_EV_DIVULGACAOENVIOS_EV_EVENTO]
GO
ALTER TABLE [dbo].[EV_DIVULGACAOENVIOS]  WITH CHECK ADD  CONSTRAINT [FK_EV_DIVULGACAOENVIOS_EV_DIVULGACAO] FOREIGN KEY([IDDIVULGACAO])
REFERENCES [dbo].[EV_DIVULGACAO] ([ID])
GO

ALTER TABLE [dbo].[EV_DIVULGACAOENVIOS] CHECK CONSTRAINT [FK_EV_DIVULGACAOENVIOS_EV_DIVULGACAO]
GO
ALTER TABLE [dbo].[EV_DIVULGACAOENVIOS]  WITH CHECK ADD  CONSTRAINT [FK_EV_DIVULGACAOENVIOS_AD_ORGAOS] FOREIGN KEY([IDORGAOTRABALHO])
REFERENCES [dbo].[AD_ORGAOS] ([ID])
GO

ALTER TABLE [dbo].[EV_DIVULGACAOENVIOS] CHECK CONSTRAINT [FK_EV_DIVULGACAOENVIOS_AD_ORGAOS]