CREATE TABLE [dbo].[EV_ESCOLARIDADE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ESCOLARIDADE] [varchar](50) NOT NULL,
	[IDESCOLARIDADEANTIGO] [int] NOT NULL,
 CONSTRAINT [PK_EV_ESCOLARIDADE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

