CREATE TABLE [dbo].[EV_EVENTOTURNOS](
	[IDEVENTO] [int] NOT NULL,
	[IDTURNO] [int] NOT NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[DTATUALIZACAO] [datetime] NOT NULL,
	[DTEXCLUSAO] [datetime] NULL,
 CONSTRAINT [PK_EV_EVENTOTURNOS] PRIMARY KEY CLUSTERED 
(
	[IDEVENTO] ASC,
	[IDTURNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
/****** Object:  Index [NonClusteredIndex-20171029-024719]    Script Date: 11/30/2017 5:47:33 PM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20171029-024719] ON [dbo].[EV_EVENTOTURNOS]
(
	[IDEVENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

