CREATE TABLE [dbo].[EV_EVENTODATAS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDEVENTO] [int] NOT NULL,
	[DTINICIO] [datetime] NOT NULL,
	[DTTERMINO] [datetime] NOT NULL,
	[HORAINICIO] [time](7) NOT NULL,
	[HORATERMINO] [time](7) NOT NULL,
 CONSTRAINT [PK_EV_EVENTODATAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
ALTER TABLE [dbo].[EV_EVENTODATAS]  WITH CHECK ADD  CONSTRAINT [FK_EV_EVENTODATAS_EV_EVENTO] FOREIGN KEY([IDEVENTO])
REFERENCES [dbo].[EV_EVENTO] ([ID])
GO

ALTER TABLE [dbo].[EV_EVENTODATAS] CHECK CONSTRAINT [FK_EV_EVENTODATAS_EV_EVENTO]