CREATE TABLE [dbo].[EV_GRUPODEQUESTOES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RECURSOID] [int] NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[DTATUALIZACAO] [datetime] NOT NULL,
	[DTEXCLUSAO] [datetime] NULL,
 CONSTRAINT [PK_EV_GRUPODEQUESTOES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
ALTER TABLE [dbo].[EV_GRUPODEQUESTOES]  WITH CHECK ADD  CONSTRAINT [FK_EV_GRUPODEQUESTOES_EV_RECURSOPROVA] FOREIGN KEY([RECURSOID])
REFERENCES [dbo].[EV_RECURSOPROVA] ([ID])
GO

ALTER TABLE [dbo].[EV_GRUPODEQUESTOES] CHECK CONSTRAINT [FK_EV_GRUPODEQUESTOES_EV_RECURSOPROVA]