CREATE TABLE [dbo].[EV_PROVAQUESTOES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GRUPOQUESTOESID] [int] NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[DTATUALIZACAO] [datetime] NOT NULL,
	[DTEXCLUSAO] [datetime] NOT NULL,
 CONSTRAINT [PK_EV_PROVAQUESTOES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
ALTER TABLE [dbo].[EV_PROVAQUESTOES]  WITH CHECK ADD  CONSTRAINT [FK_EV_PROVAQUESTOES_EV_GRUPODEQUESTOES] FOREIGN KEY([GRUPOQUESTOESID])
REFERENCES [dbo].[EV_GRUPODEQUESTOES] ([ID])
GO

ALTER TABLE [dbo].[EV_PROVAQUESTOES] CHECK CONSTRAINT [FK_EV_PROVAQUESTOES_EV_GRUPODEQUESTOES]