CREATE TABLE [dbo].[EV_QUESTOESCORRECAO](
	[ID] [int] NOT NULL,
	[GRUPOQUESTOESID] [int] NOT NULL,
	[DESCRICAO] [int] NOT NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[DTATUALIZACAO] [datetime] NOT NULL,
	[DTEXCLUSAO] [datetime] NULL,
 CONSTRAINT [PK_EV_QUESTOESCORRECAO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
ALTER TABLE [dbo].[EV_QUESTOESCORRECAO]  WITH CHECK ADD  CONSTRAINT [FK_EV_QUESTOESCORRECAO_EV_GRUPODEQUESTOES] FOREIGN KEY([GRUPOQUESTOESID])
REFERENCES [dbo].[EV_GRUPODEQUESTOES] ([ID])
GO

ALTER TABLE [dbo].[EV_QUESTOESCORRECAO] CHECK CONSTRAINT [FK_EV_QUESTOESCORRECAO_EV_GRUPODEQUESTOES]