CREATE TABLE [dbo].[EV_TIPOEVENTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](50) NOT NULL,
	[DTALTERACAO] [datetime] NOT NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[DTEXCLUSAO] [datetime] NULL,
 CONSTRAINT [PK_EV_TIPOEVENTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
ALTER TABLE [dbo].[EV_TIPOEVENTO] ADD  CONSTRAINT [DF_EV_TIPOEVENTO_DTCADASTRO]  DEFAULT (getdate()) FOR [DTCADASTRO]
GO
ALTER TABLE [dbo].[EV_TIPOEVENTO] ADD  CONSTRAINT [DF_EV_TIPOEVENTO_DTALTERACAO]  DEFAULT (getdate()) FOR [DTALTERACAO]