CREATE TABLE [adm].[AD_MUNICIPIO](
	[NU_MUNICIPIO] [int] NOT NULL,
	[NO_MUNICIPIO] [varchar](50) NOT NULL,
	[SG_UF] [nvarchar](3) NOT NULL,
	[CO_DDD] [nvarchar](3) NULL,
 CONSTRAINT [PK_TB002_MUNICIPIO] PRIMARY KEY NONCLUSTERED 
(
	[NU_MUNICIPIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

