CREATE TABLE [adm].[AD_ORGAOEMISSOR](
	[CO_EMISSOR] [varchar](50) NOT NULL,
	[NO_EMISSOR] [varchar](70) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CO_EMISSOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

