CREATE TABLE [adm].[AD_UF](
	[SG_UF] [varchar](2) NOT NULL,
	[NO_UF] [varchar](20) NOT NULL,
	[NO_REGIAO] [varchar](20) NULL,
	[NO_PAIS] [varchar](20) NULL,
 CONSTRAINT [PK_TB001_UF] PRIMARY KEY NONCLUSTERED 
(
	[SG_UF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

