CREATE TABLE [escola].[ES_INSTITUICOES](
	[ID] [int] NOT NULL,
	[DPADMID] [int] NOT NULL,
	[NOME] [varchar](200) NOT NULL,
	[SIGLA] [varchar](10) NOT NULL,
	[UF] [varchar](2) NOT NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[DTATUALIZACAO] [datetime] NOT NULL,
	[DTEXCLUSAO] [datetime] NULL,
 CONSTRAINT [PK_ES_INSTITUICOES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'INSTITUICOES UNIVERSIDADES E ESCOLAS' , @level0type=N'SCHEMA',@level0name=N'escola', @level1type=N'TABLE',@level1name=N'ES_INSTITUICOES'


GO
ALTER TABLE [escola].[ES_INSTITUICOES]  WITH CHECK ADD  CONSTRAINT [FK_ES_INSTITUICOES_ES_INSTITUICOES] FOREIGN KEY([DPADMID])
REFERENCES [escola].[ES_DEPENDENCIAADMINISTRATIVA] ([ID])
GO

ALTER TABLE [escola].[ES_INSTITUICOES] CHECK CONSTRAINT [FK_ES_INSTITUICOES_ES_INSTITUICOES]